---

- hosts: staging
  become: yes
  tasks:

  - name: update nodejs package 
    ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_15.x | sudo -E bash -

  - name: install nodejs
    apt:
      name: nodejs
      state: present
  
  - name: Creates directory
    file:
      path: /src/www
      state: directory

  # - name: getting artifact
  #   ansible.builtin.unarchive:
  #     src: http://10.0.0.4:8080/job/weightCI/lastSuccessfulBuild/artifact/latest.zip
  #     dest: /src/www
  #     remote_src: yes    

  - name: Download artifact
    get_url:
      url: http://10.0.0.4:8080/job/weightCI/lastSuccessfulBuild/artifact/latest.zip
      dest: /src/www
      username: smallpox
      password: 11672cb09384ada7e9e51ff1ad539dba0e

  - name: Extract artifact
    ansible.builtin.unarchive:
      src: /src/www/latest.zip
      dest: /src/www

  - name: create .env
    ansible.builtin.script: buildEnv.sh -u {{ hostvars['staging'].okta_url }} -i {{ hostvars['staging'].okta_id }} -s {{ hostvars['staging'].okta_secret }} -h {{ hostvars['staging'].db_host }} -p {{ hostvars['staging'].db_pass }} -n {{ hostvars['staging'].db_user }}

  - name: initialize db
    ansible.builtin.shell: node /src/www/tools/initdb.js

  - name: run app
    ansible.builtin.shell: node /src/www/src/index.js

# 11672cb09384ada7e9e51ff1ad539dba0e